#!/usr/bin/env bash

source src/_helpers/outputUtils.sh

function runAll() {
    echo "
Gnuplot Examples
----------------

This project is created for learning purpose.

It started as a side project when I was looking for a simple, battery-included plotting utility to
implement a software profiling toolkit at work.

Gnuplot stood out of all the candidates because:

- It creates decent 2D graphs.

- It has the least amount of dependencies.
I can either download and unzip the binary or build it from the source.
After that it is fully functional (you can verify that by running all
the example scripts below).

- It uses text files as the main source of input data. This greatly simplifies the tooling.

- It is hackable via scripting but does not force the users to learn another programming language.
Matlab and Python's Metaplot are great but to entry-level users the learning curve can be steep.

This project is loosely based on the examples in
[Gnuplot in Action, second edition](https://www.manning.com/books/gnuplot-in-action-second-edition).

All the examples were written and tested on Ubuntu 16.


Script Gallery
--------------
" > ./README.md
    local _pwd=$( pwd )
    local relImgPath=
    local relImgPathDst=
    local relSrcPath=
    local outPath=
    for n in $( find $1 -type f \
    -not -path "*git/*" \
    -not -path "*_ex/*" \
    -not -path "*_testdata/*" \
    -not -path "*_helpers/*" \
    -name "*.sh" )
    do
        outPath=`setPNGOutput ${n}`
        relImgPath=`generateName pngs ${n}`
        relImgPathDst=`generateName ${PNG_OUTPUT_DIR} ${n}`
        echo ${outPath}
        echo ${relImgPath}
        if ( ! PNG_OUTPUT=${outPath} bash ${n} )
        then
            echo "failed to execute: " ${n}
            exit 1
        fi
        if ( ! convert ${relImgPathDst} -resize 360x360 ${relImgPathDst} )
        then
            echo "failed to resize: " ${relImgPathDst}
            exit 1
        fi
        echo "
[${n##*/src/}](src/${n##*/src/})

![alt text](${relImgPath})

" >> ./README.md
    done
    cd ${_pwd}
}

function run() {
    runAll $1
}

function resetOutputDir() {
    local _dir=$1
    rm -rf ${_dir}
    mkdir ${_dir}
    export PNG_OUTPUT_DIR=${_dir}
}

function setTestdataDir() {
    export TESTDATA_DIR=$( pwd )/src/_testdata
}

setTestdataDir
resetOutputDir "/tmp/gnuplotPngs"
run $( pwd )
cp -rf ${PNG_OUTPUT_DIR}/* ./pngs
